os: Visual Studio 2015
version: 1.0.{build}

environment:
  CLI_VERSION: 1.0.0-preview2-003121

branches:
  only:
    - master

install:
  - ps: npm install npm@3.10.6 -g
  - ps: npm -v
  - ps: npm install -g bower --loglevel=error
  - ps: npm install -g gulp --loglevel=error

build_script:
  - ps: dotnet --info
  - ps: .\Build.ps1

artifacts:
  - path: artifacts\publish

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off
